from services.retrieval_service import retrieval_service
from services.llm_service import call_llama, build_reasoning_prompt

def generate_response(
    query: str,
    document_ids: list[int] | None,
    document_names: dict[int, str]
) -> dict:
    """
    Main RAG pipeline. Called from chat.py.

    Args:
        query         : the user's question
        document_ids  : list of doc IDs to search (None = search all indexed)
        document_names: { doc_id: filename } for source attribution

    Returns dict with keys: answer, reasoning, pros, cons, risks, recommendation
    (mapped to ChatResponse by chat.py)
    """
    print(f"[RAG] Query='{query[:80]}' | doc_ids={document_ids}")

    # --- RETRIEVAL ---
    results = retrieval_service.search(
        query=query,
        doc_ids=document_ids if document_ids else None,
        top_k=5
    )

    if not results:
        print("[RAG] No chunks retrieved — falling back to no-context response")
        return _no_context_response(query)

    context = "\n\n---\n\n".join([r["chunk"] for r in results])
    used_doc_ids = list(set(r["doc_id"] for r in results))
    source_names = [document_names.get(did, f"Document {did}") for did in used_doc_ids]

    # --- GENERATION PATH (Llama3) ---
    try:
        prompt = build_reasoning_prompt(query, context)
        answer = call_llama(prompt)
        return {
            "answer": answer,
            "reasoning": "Answer generated by Llama3 using retrieved document context.",
            "pros": ["Synthesized and explained by local LLM"],
            "cons": ["Response time depends on local hardware"],
            "risks": ["LLM may supplement with general knowledge where document is silent"],
            "recommendation": "",
            "sources": source_names
        }
    except RuntimeError as e:
        print(f"[RAG] Llama3 call failed: {e}")
        return {
            "answer": f"Could not generate a reasoned answer. Ollama error: {e}\n\n"
                      f"Raw document context:\n{context}",
            "reasoning": "LLM call failed — returning raw retrieved context as fallback.",
            "pros": [],
            "cons": ["LLM unavailable"],
            "risks": [],
            "recommendation": "Ensure Ollama is running: ollama serve",
            "sources": source_names
        }


def _no_context_response(query: str) -> dict:
    return {
        "answer": "No relevant content found in the uploaded documents for this query.",
        "reasoning": "TF-IDF retrieval returned no chunks above the relevance threshold.",
        "pros": [],
        "cons": ["No document context available"],
        "risks": [],
        "recommendation": "Try rephrasing your query, or upload a relevant document first.",
        "sources": []
    }
